name: Continuous Integration
on: push
env:
  DB_NAME: test
  DB_USER: root
  DB_PASSWORD: abcd@efg

jobs:
  run_code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Set up mysql
        run: |
          sudo /etc/init.d/mysql start
          sudo mysql -e "ALTER USER '${{ env.DB_USER }}'@'localhost' IDENTIFIED WITH mysql_native_password BY '${{ env.DB_PASSWORD }}';"
          sudo mysql -e "CREATE DATABASE IF NOT EXISTS ${{env.DB_NAME}};" -u${{env.DB_USER}} -p${{env.DB_PASSWORD}}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Change directory
        run: cd my-inventory

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21' # Or the latest stable version

      - name: Linting
        run: |
          go fmt ./...
          go vet ./...

      - name: Run tests
        run: go test